/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import controller.datahotelcontroller;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Bagus Duta Prasetya
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    datahotelcontroller dc;
    public MainView() {
        initComponents();
        dc = new datahotelcontroller(this);
        dc.isitabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHotel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtNama = new javax.swing.JTextField();
        TxtNohp = new javax.swing.JTextField();
        TxtNokamar = new javax.swing.JTextField();
        TxtLama = new javax.swing.JTextField();
        CbTipe = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        TxtId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnclear1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelHotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelHotelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelHotel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, 591, 242));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Pemesan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 147, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No Hp");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 173, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No Kamar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 199, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipe Kamar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 225, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lama Menginap");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 251, -1, -1));

        TxtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 145, 148, -1));

        TxtNohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNohpActionPerformed(evt);
            }
        });
        getContentPane().add(TxtNohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 171, 148, -1));
        getContentPane().add(TxtNokamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 197, 148, -1));
        getContentPane().add(TxtLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 249, 147, -1));

        CbTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Superior", "Deluxe", "Family", "Suite" }));
        CbTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbTipeActionPerformed(evt);
            }
        });
        getContentPane().add(CbTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 223, 148, -1));

        btnTambah.setText("Rersevasi");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 287, 100, -1));

        TxtId.setEditable(false);
        getContentPane().add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 370, 910, 10));
        TxtId.getAccessibleContext().setAccessibleName("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        btnDelete.setText("Checkout");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 316, 100, -1));

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 316, 100, -1));

        btnclear1.setText("Clear");
        btnclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 243, 286, 0));

        btnUpdate.setText("Ganti Data");
        btnUpdate.setMaximumSize(new java.awt.Dimension(79, 23));
        btnUpdate.setMinimumSize(new java.awt.Dimension(79, 23));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 287, 100, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PEMESANAN HOTEL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 40, 277, 28));

        btnLogout.setBackground(new java.awt.Color(255, 204, 204));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 93, 148, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cari Nama :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/f1dd40d36b17542578727c3d6e863903.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        dc.insert();
        dc.isitabel();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void CbTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbTipeActionPerformed
        
    }//GEN-LAST:event_CbTipeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        dc.delete();
        dc.isitabel();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tabelHotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelHotelMouseClicked
        int baris = tabelHotel.getSelectedRow();
        TxtId.setText(tabelHotel.getValueAt(baris, 0).toString());
        TxtNama.setText(tabelHotel.getValueAt(baris, 1).toString());
        TxtNohp.setText(tabelHotel.getValueAt(baris, 2).toString());
        TxtNokamar.setText(tabelHotel.getValueAt(baris, 3).toString());
        CbTipe.setSelectedItem(tabelHotel.getValueAt(baris, 4).toString());
        TxtLama.setText(tabelHotel.getValueAt(baris, 5).toString());
    }//GEN-LAST:event_tabelHotelMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        TxtId.setText("");
        TxtNama.setText("");
        TxtNohp.setText("");
        TxtNokamar.setText("");
        CbTipe.setSelectedItem(null); 
        TxtLama.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclear1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        dc.update();
        dc.isitabel();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm =JOptionPane.showConfirmDialog(this,"Anda yakin ingin Log Out?","Keluar Aplikasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION){
                JFrame LoginPage;
                LoginPage = new LoginPage();
                LoginPage.setVisible(true);
                LoginPage.setLocationRelativeTo(null);
                this.dispose();
            }
             if(confirm == JOptionPane.NO_OPTION){
        
            }
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        dc.search();
    }//GEN-LAST:event_txtSearchActionPerformed

    private void TxtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaActionPerformed

    private void TxtNohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNohpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbTipe;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtLama;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtNohp;
    private javax.swing.JTextField TxtNokamar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclear1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelHotel;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public JTable getTabelHotel() {
        return tabelHotel;
    }

    public void setTabelHotel(JTable tabelHotel) {
        this.tabelHotel = tabelHotel;
    }

    public JTextField getTxtId() {
        return TxtId;
    }

    public void setTxtId(JTextField txtId) {
        this.TxtId = txtId;
    }

    public JComboBox<String> getCbTipe() {
        return CbTipe;
    }

    public void setCbTipe(JComboBox<String> cbTipe) {
        this.CbTipe = cbTipe;
    }

    public JTextField getTxtLama() {
        return TxtLama;
    }

    public void setTxtLama(JTextField txtLama) {
        this.TxtLama = txtLama;
    }

    public JTextField getTxtNama() {
        return TxtNama;
    }

    public void setTxtNama(JTextField txtNama) {
        this.TxtNama = txtNama;
    }

    public JTextField getTxtNohp() {
        return TxtNohp;
    }

    public void setTxtNohp(JTextField txtNohp) {
        this.TxtNohp = txtNohp;
    }

    public JTextField getTxtNokamar() {
        return TxtNokamar;
    }

    public void setTxtNokamar(JTextField txtNokamar) {
        this.TxtNokamar = txtNokamar;
    }

    public JTextField getTxtSearch() {
        return txtSearch;
    }

    public void setTxtSearch(JTextField txtSearch) {
        this.txtSearch = txtSearch;
    }
    
    
}
